# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PasportEye.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.setFixedSize(649, 496)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("\n"
"\n"
"/*Vertical*/\n"
"QScrollBar:vertical{\n"
"    border: none;\n"
"    background-color: rgb(66, 66, 89);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"\n"
"/* Hadler vertical*/\n"
"\n"
"QScrollBar::handle:vertical{\n"
"    background-color: rgb(93, 93, 125);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"    background-color: rgb(55, 98, 199);\n"
"}\n"
"QScrollBar::handle:vertical:pressed{\n"
"    \n"
"    background-color: rgb(39, 70, 143);\n"
"}\n"
"\n"
"/*BTN TOP-SCROLLBAR*/\n"
"QScrollBar::sub-line:vertical{\n"
"    border:none;\n"
"    background-color: rgb(66, 66, 89);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-poosition: top;\n"
"    subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover{\n"
"    background-color: rgb(55, 98, 199);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed{\n"
"    background-color: rgb(39, 70, 143);\n"
"}\n"
"\n"
"\n"
"/*BTN BOTTOM-SCROLLBAR*/\n"
"QScrollBar::add-line:vertical{\n"
"    border:none;\n"
"    background-color: rgb(66, 66, 89);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-poosition: bottom;\n"
"    subcontrol-origin:margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover{\n"
"    background-color: rgb(55, 98, 199);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed{\n"
"    background-color: rgb(39, 70, 143);\n"
"}\n"
"\n"
"\n"
"/*RESET ARROW*/\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical{\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical{\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/*HORIZONTA NEW LINE*/\n"
"\n"
"QScrollBar:horizontal{\n"
"    border: none;\n"
"    background-color: rgb(66, 66, 89);\n"
"    border: none;\n"
"    background-color: rgb(66, 66, 89);\n"
"    height: 15px;\n"
"     margin: 0px 20px 0 20px;\n"
"    \n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal{\n"
"    background-color: rgb(93, 93, 125);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"    \n"
"}\n"
"QScrollBar::handle:horizontal:hover{\n"
"    background-color: rgb(55, 98, 199);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed{\n"
"    \n"
"    background-color: rgb(39, 70, 143);\n"
"}\n"
"\n"
"/*BTN TOP-SCROLLBAR*/\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"     border: none;\n"
"     background-color: rgb(66, 66, 89);\n"
"     width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: right;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::sub-line:horizontal {\n"
"     border: none;\n"
"     background-color: rgb(66, 66, 89);\n"
"     width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
"QScrollBar::add-line:horizontal:hover{\n"
"    background-color: rgb(55, 98, 199);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed{\n"
"    background-color: rgb(39, 70, 143);\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal:hover{\n"
"    background-color: rgb(55, 98, 199);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed{\n"
"    background-color: rgb(39, 70, 143);\n"
"}\n"
"\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal{\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal{\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("background-color: #22222e")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 0, 651, 191))
        self.frame.setStyleSheet("\n"
"background-color: rgb(55, 98, 199);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(-40, 10, 311, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Resourse/logo.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(60, 140, 251, 20))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.choose_pass = QtWidgets.QPushButton(self.centralwidget)
        self.choose_pass.setGeometry(QtCore.QRect(30, 220, 291, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_pass.sizePolicy().hasHeightForWidth())
        self.choose_pass.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("EngraversGothic BT")
        font.setPointSize(10)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.choose_pass.setFont(font)
        self.choose_pass.setMouseTracking(False)
        self.choose_pass.setFocusPolicy(QtCore.Qt.NoFocus)
        self.choose_pass.setAutoFillBackground(False)
        self.choose_pass.setStyleSheet("QPushButton{\n"
"background-color: #22222e;\n"
"border: 2px solid #2f55a7;\n"
"border-radius: 20;\n"
"color:white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 85, 255);\n"
"    \n"
"\n"
"}\n"
"\n"
"")
        self.choose_pass.setObjectName("choose_pass")
        self.choose_json = QtWidgets.QPushButton(self.centralwidget)
        self.choose_json.setGeometry(QtCore.QRect(30, 290, 291, 41))
        font = QtGui.QFont()
        font.setFamily("EngraversGothic BT")
        font.setPointSize(10)
        self.choose_json.setFont(font)
        self.choose_json.setFocusPolicy(QtCore.Qt.NoFocus)
        self.choose_json.setStyleSheet("QPushButton{\n"
"background-color: #22222e;\n"
"border: 2px solid #2f55a7;\n"
"border-radius: 20;\n"
"color:white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 85, 255);\n"
"    \n"
"\n"
"}")
        self.choose_json.setObjectName("choose_json")
        self.process = QtWidgets.QPushButton(self.centralwidget)
        self.process.setGeometry(QtCore.QRect(30, 360, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Eras Medium ITC")
        font.setPointSize(10)
        self.process.setFont(font)
        self.process.setFocusPolicy(QtCore.Qt.NoFocus)
        self.process.setStyleSheet("QPushButton{\n"
"background-color: #22222e;\n"
"border: 2px solid #2f55a7;\n"
"border-radius: 20;\n"
"color:white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 85, 255);\n"
"    \n"
"\n"
"}")
        self.process.setObjectName("process")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(30, 440, 291, 41))
        font = QtGui.QFont()
        font.setFamily("EngraversGothic BT")
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(34, 34, 46);\n"
"    border:  solid #2f55a7;\n"
"    border-radius: 20px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 18px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.274862 rgba(60, 98, 204, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(340, 10, 301, 471))
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"border: 2px solid #2f55a7;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1222, 1222))
        self.scrollAreaWidgetContents.setStyleSheet("border: 2px solid #2f55a7;\n"
"border-radius: 20px;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setMinimumSize(QtCore.QSize(1200, 1200))
        self.frame_2.setStyleSheet("border:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.load_data = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.load_data.setFont(font)
        self.load_data.setStyleSheet("color: rgb(255, 255, 255);")
        self.load_data.setMidLineWidth(0)
        self.load_data.setText("")
        self.load_data.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.load_data.setWordWrap(False)
        self.load_data.setObjectName("load_data")
        self.gridLayout.addWidget(self.load_data, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculate "))
        self.label_3.setText(_translate("MainWindow", "EyePassport "))
        self.choose_pass.setText(_translate("MainWindow", "Выбрать Паспорт"))
        self.choose_json.setText(_translate("MainWindow", "JSON"))
        self.process.setText(_translate("MainWindow", "Обработка"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
